PANDAS PRACTICE

Pandas Tutorial

Pandas is an open-source, BSD-licensed Python library that provides high-performance, easy-to-use data structures and powerful data analysis tools.

Agenda
1. What is a DataFrame?
2. What is a Series?
3. Different Operations in Pandas

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Playing with Dataframe

df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns= ['Col1', 'Col2', 'Col3', 'Col4'])

In [5]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [6]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [7]:
df.head

<bound method NDFrame.head of       Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19>

In [8]:
df.head()

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [9]:
df.to_csv('try.csv')

In [10]:
#Accessing the elements

#1. loc (row index mainly)
#2. iloc (both row and column index)

df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [11]:
type(df.loc['Row1'])

pandas.core.series.Series

In [12]:
df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [13]:
df.iloc[0:3,1:3]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10

In [14]:
type(df.iloc[0:3,1:3])

pandas.core.frame.DataFrame

In [15]:
#convert Dataframes into an array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [16]:
df.iloc[:,1:].values.shape

(5, 3)

In [17]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [18]:
df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

In [19]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [20]:
df['Col3']

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Col3, dtype: int32

In [21]:
df[['Col2', 'Col3']]

      Col2  Col3
Row1     1     2
Row2     5     6
Row3     9    10
Row4    13    14
Row5    17    18

In [22]:
df.describe()

            Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 292.0+ bytes

In [24]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [25]:
df = pd.read_csv('mercedesbenzyes.csv')

In [26]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [27]:
# Get unique category counts\
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [28]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

CSV

In [29]:
from io import StringIO, BytesIO

In [30]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [31]:
type(data)

str

In [32]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [33]:
df = pd.read_csv(StringIO(data),usecols=['col1', 'col2'])

In [34]:
df

  col1 col2
0    x    y
1    a    b
2    c    d

In [35]:
df.to_csv('Test.csv')

In [36]:
#Specifying columns data types

data = ('a,b,c,d \n'
        '1,2,3,4 \n'
        '5,6,7,8\n'
        '9,10,11')

In [37]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [38]:
df = pd.read_csv(StringIO(data),dtype=float)

In [39]:
df

     a     b     c   d
0  1.0   2.0   3.0  4.0
1  5.0   6.0   7.0  8.0
2  9.0  10.0  11.0  NaN

In [40]:
df['a'][1]

5.0

In [41]:
df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_24180\566591662.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df = pd.read_csv(StringIO(data), dtype = {'b':int,'c':np.float,'a': 'Int64'})

In [42]:
df

   a   b     c   d
0  1   2   3.0  4.0
1  5   6   7.0  8.0
2  9  10  11.0  NaN

In [43]:
df.dtypes

a       Int64
b       int32
c     float64
d     float64
dtype: object

In [44]:
data = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [45]:
pd.read_csv(StringIO(data),index_col = 0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [46]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,\n')

In [47]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [48]:
df = pd.read_csv(StringIO(data),index_col=False)

In [49]:
df = pd.read_csv(StringIO(data),usecols=['b', 'c'],index_col=False)

In [50]:
df

        b    c
0   apple  bat
1  orange  cow

In [51]:
#Quoting and Escape Characters. Very useful in NLP

data = 'a, b,\n "hello, \\Bob\\", nice to see you",5'

In [52]:
df = pd.read_csv(StringIO(data),escapechar='\\')

In [53]:
df

             a                  b  Unnamed: 2
 "hello   Bob"   nice to see you"           5

In [54]:
#URL TO CSV

# df = pd.read_csv(
#     'https://download.bls.gov/pub/time.series/cu/cu.item',
#     sep='\t'
# )

READ JSON TO CSV

In [ ]:
import pandas as pd
import json

Data = [
    {"Name": "Alice", "Age": 25, "City": "Kathmandu"},
    {"Name": "Bob", "Age": 30, "City": "Pokhara"},
    {"Name": "Charlie", "Age": 28, "City": "Lalitpur"}
]



json_str = json.dumps(Data)   # Convert list of dicts to JSON string
df = pd.read_json(json_str)
print(df)

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur

In [ ]:
import pandas as pd


url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"

df2 = pd.read_csv(url, encoding="latin1", header=None,)
print(df2.head())

In [5]:
df.to_json(orient="records")

'[{"Class":1,"Alcohol":14.23,"Malic_acid":1.71,"Ash":2.43,"Alcalinity_of_ash":15.6,"Magnesium":127,"Total_phenols":2.8,"Flavanoids":3.06,"Nonflavanoid_phenols":0.28,"Proanthocyanins":2.29,"Color_intensity":5.64,"Hue":1.04,"OD280\\/OD315_of_diluted_wines":3.92,"Proline":1065},{"Class":1,"Alcohol":13.2,"Malic_acid":1.78,"Ash":2.14,"Alcalinity_of_ash":11.2,"Magnesium":100,"Total_phenols":2.65,"Flavanoids":2.76,"Nonflavanoid_phenols":0.26,"Proanthocyanins":1.28,"Color_intensity":4.38,"Hue":1.05,"OD280\\/OD315_of_diluted_wines":3.4,"Proline":1050},{"Class":1,"Alcohol":13.16,"Malic_acid":2.36,"Ash":2.67,"Alcalinity_of_ash":18.6,"Magnesium":101,"Total_phenols":2.8,"Flavanoids":3.24,"Nonflavanoid_phenols":0.3,"Proanthocyanins":2.81,"Color_intensity":5.68,"Hue":1.03,"OD280\\/OD315_of_diluted_wines":3.17,"Proline":1185},{"Class":1,"Alcohol":14.37,"Malic_acid":1.95,"Ash":2.5,"Alcalinity_of_ash":16.8,"Magnesium":113,"Total_phenols":3.85,"Flavanoids":3.49,"Nonflavanoid_phenols":0.24,"Proanthocyanins":2.18,"Color_intensity":7.8,"Hue":0.86,"OD280\\/OD315_of_diluted_wines":3.45,"Proline":1480},{"Class":1,"Alcohol":13.24,"Malic_acid":2.59,"Ash":2.87,"Alcalinity_of_ash":21.0,"Magnesium":118,"Total_phenols":2.8,"Flavanoids":2.69,"Nonflavanoid_phenols":0.39,"Proanthocyanins":1.82,"Color_intensity":4.32,"Hue":1.04,"OD280\\/OD315_of_diluted_wines":2.93,"Proline":735},{"Class":1,"Alcohol":14.2,"Malic_acid":1.76,"Ash":2.45,"Alcalinity_of_ash":15.2,"Magnesium":112,"Total_phenols":3.27,"Flavanoids":3.39,"Nonflavanoid_phenols":0.34,"Proanthocyanins":1.97,"Color_intensity":6.75,"Hue":1.05,"OD280\\/OD315_of_diluted_wines":2.85,"Proline":1450},{"Class":1,"Alcohol":14.39,"Malic_acid":1.87,"Ash":2.45,"Alcalinity_of_ash":14.6,"Magnesium":96,"Total_phenols":2.5,"Flavanoids":2.52,"Nonflavanoid_phenols":0.3,"Proanthocyanins":1.98,"Color_intensity":5.25,"Hue":1.02,"OD280\\/OD315_of_diluted_wines":3.58,"Proline":1290},{"Class":1,"Alcohol":14.06,"Malic_acid":2.15,"Ash":2.61,"Alcalinity_of_ash":17.6,"Magnesium":121,"Total_phenols":2.6,"Flavanoids":2.51,"Nonflavanoid_phenols":0.31,"Proanthocyanins":1.25,"Color_intensity":5.05,"Hue":1.06,"OD280\\/OD315_of_diluted_wines":3.58,"Proline":1295},{"Class":1,"Alcohol":14.83,"Malic_acid":1.64,"Ash":2.17,"Alcalinity_of_ash":14.0,"Magnesium":97,"Total_phenols":2.8,"Flavanoids":2.98,"Nonflavanoid_phenols":0.29,"Proanthocyanins":1.98,"Color_intensity":5.2,"Hue":1.08,"OD280\\/OD315_of_diluted_wines":2.85,"Proline":1045},{"Class":1,"Alcohol":13.86,"Malic_acid":1.35,"Ash":2.27,"Alcalinity_of_ash":16.0,"Magnesium":98,"Total_phenols":2.98,"Flavanoids":3.15,"Nonflavanoid_phenols":0.22,"Proanthocyanins":1.85,"Color_intensity":7.22,"Hue":1.01,"OD280\\/OD315_of_diluted_wines":3.55,"Proline":1045},{"Class":1,"Alcohol":14.1,"Malic_acid":2.16,"Ash":2.3,"Alcalinity_of_ash":18.0,"Magnesium":105,"Total_phenols":2.95,"Flavanoids":3.32,"Nonflavanoid_phenols":0.22,"Proanthocyanins":2.38,"Color_intensity":5.75,"Hue":1.25,"OD280\\/OD315_of_diluted_wines":3.17,"Proline":1510},{"Class":1,"Alcohol":14.12,"Malic_acid":1.48,"Ash":2.32,"Alcalinity_of_ash":16.8,"Magnesium":95,"Total_phenols":2.2,"Flavanoids":2.43,"Nonflavanoid_phenols":0.26,"Proanthocyanins":1.57,"Color_intensity":5.0,"Hue":1.17,"OD280\\/OD315_of_diluted_wines":2.82,"Proline":1280},{"Class":1,"Alcohol":13.75,"Malic_acid":1.73,"Ash":2.41,"Alcalinity_of_ash":16.0,"Magnesium":89,"Total_phenols":2.6,"Flavanoids":2.76,"Nonflavanoid_phenols":0.29,"Proanthocyanins":1.81,"Color_intensity":5.6,"Hue":1.15,"OD280\\/OD315_of_diluted_wines":2.9,"Proline":1320},{"Class":1,"Alcohol":14.75,"Malic_acid":1.73,"Ash":2.39,"Alcalinity_of_ash":11.4,"Magnesium":91,"Total_phenols":3.1,"Flavanoids":3.69,"Nonflavanoid_phenols":0.43,"Proanthocyanins":2.81,"Color_intensity":5.4,"Hue":1.25,"OD280\\/OD315_of_diluted_wines":2.73,"Proline":1150},{"Class":1,"Alcohol":14.38,"Malic_acid":1.87,"Ash":2.38,"Alcalinity_of_ash":12.0,"Magnesium":102,"Total_phenols":3.3,"Flavanoids":3.64,"Nonflavanoid_phenols":0.29,"Proanthocyanins":2.96,"Color_intensity":7.5,"Hue":1.2,"OD280\\/OD315_of_diluted_wines":3.0,"Proline":1547},{"Class":1,"Alcohol":13.63,"Malic_acid":1.81,"Ash":2.7,"Alcalinity_of_ash":17.2,"Magnesium":112,"Total_phenols":2.85,"Flavanoids":2.91,"Nonflavanoid_phenols":0.3,"Proanthocyanins":1.46,"Color_intensity":7.3,"Hue":1.28,"OD280\\/OD315_of_diluted_wines":2.88,"Proline":1310},{"Class":1,"Alcohol":14.3,"Malic_acid":1.92,"Ash":2.72,"Alcalinity_of_ash":20.0,"Magnesium":120,"Total_phenols":2.8,"Flavanoids":3.14,"Nonflavanoid_phenols":0.33,"Proanthocyanins":1.97,"Color_intensity":6.2,"Hue":1.07,"OD280\\/OD315_of_diluted_wines":2.65,"Proline":1280},{"Class":1,"Alcohol":13.83,"Malic_acid":1.57,"Ash":2.62,"Alcalinity_of_ash":20.0,"Magnesium":115,"Total_phenols":2.95,"Flavanoids":3.4,"Nonflavanoid_phenols":0.4,"Proanthocyanins":1.72,"Color_intensity":6.6,"Hue":1.13,"OD280\\/OD315_of_diluted_wines":2.57,"Proline":1130},{"Class":1,"Alcohol":14.19,"Malic_acid":1.59,"Ash":2.48,"Alcalinity_of_ash":16.5,"Magnesium":108,"Total_phenols":3.3,"Flavanoids":3.93,"Nonflavanoid_phenols":0.32,"Proanthocyanins":1.86,"Color_intensity":8.7,"Hue":1.23,"OD280\\/OD315_of_diluted_wines":2.82,"Proline":1680},{"Class":1,"Alcohol":13.64,"Malic_acid":3.1,"Ash":2.56,"Alcalinity_of_ash":15.2,"Magnesium":116,"Total_phenols":2.7,"Flavanoids":3.03,"Nonflavanoid_phenols":0.17,"Proanthocyanins":1.66,"Color_intensity":5.1,"Hue":0.96,"OD280\\/OD315_of_diluted_wines":3.36,"Proline":845},{"Class":1,"Alcohol":14.06,"Malic_acid":1.63,"Ash":2.28,"Alcalinity_of_ash":16.0,"Magnesium":126,"Total_phenols":3.0,"Flavanoids":3.17,"Nonflavanoid_phenols":0.24,"Proanthocyanins":2.1,"Color_intensity":5.65,"Hue":1.09,"OD280\\/OD315_of_diluted_wines":3.71,"Proline":780},{"Class":1,"Alcohol":12.93,"Malic_acid":3.8,"Ash":2.65,"Alcalinity_of_ash":18.6,"Magnesium":102,"Total_phenols":2.41,"Flavanoids":2.41,"Nonflavanoid_phenols":0.25,"Proanthocyanins":1.98,"Color_intensity":4.5,"Hue":1.03,"OD280\\/OD315_of_diluted_wines":3.52,"Proline":770},{"Class":1,"Alcohol":13.71,"Malic_acid":1.86,"Ash":2.36,"Alcalinity_of_ash":16.6,"Magnesium":101,"Total_phenols":2.61,"Flavanoids":2.88,"Nonflavanoid_phenols":0.27,"Proanthocyanins":1.69,"Color_intensity":3.8,"Hue":1.11,"OD280\\/OD315_of_diluted_wines":4.0,"Proline":1035},{"Class":1,"Alcohol":12.85,"Malic_acid":1.6,"Ash":2.52,"Alcalinity_of_ash":17.8,"Magnesium":95,"Total_phenols":2.48,"Flavanoids":2.37,"Nonflavanoid_phenols":0.26,"Proanthocyanins":1.46,"Color_intensity":3.93,"Hue":1.09,"OD280\\/OD315_of_diluted_wines":3.63,"Proline":1015},{"Class":1,"Alcohol":13.5,"Malic_acid":1.81,"Ash":2.61,"Alcalinity_of_ash":20.0,"Magnesium":96,"Total_phenols":2.53,"Flavanoids":2.61,"Nonflavanoid_phenols":0.28,"Proanthocyanins":1.66,"Color_intensity":3.52,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":3.82,"Proline":845},{"Class":1,"Alcohol":13.05,"Malic_acid":2.05,"Ash":3.22,"Alcalinity_of_ash":25.0,"Magnesium":124,"Total_phenols":2.63,"Flavanoids":2.68,"Nonflavanoid_phenols":0.47,"Proanthocyanins":1.92,"Color_intensity":3.58,"Hue":1.13,"OD280\\/OD315_of_diluted_wines":3.2,"Proline":830},{"Class":1,"Alcohol":13.39,"Malic_acid":1.77,"Ash":2.62,"Alcalinity_of_ash":16.1,"Magnesium":93,"Total_phenols":2.85,"Flavanoids":2.94,"Nonflavanoid_phenols":0.34,"Proanthocyanins":1.45,"Color_intensity":4.8,"Hue":0.92,"OD280\\/OD315_of_diluted_wines":3.22,"Proline":1195},{"Class":1,"Alcohol":13.3,"Malic_acid":1.72,"Ash":2.14,"Alcalinity_of_ash":17.0,"Magnesium":94,"Total_phenols":2.4,"Flavanoids":2.19,"Nonflavanoid_phenols":0.27,"Proanthocyanins":1.35,"Color_intensity":3.95,"Hue":1.02,"OD280\\/OD315_of_diluted_wines":2.77,"Proline":1285},{"Class":1,"Alcohol":13.87,"Malic_acid":1.9,"Ash":2.8,"Alcalinity_of_ash":19.4,"Magnesium":107,"Total_phenols":2.95,"Flavanoids":2.97,"Nonflavanoid_phenols":0.37,"Proanthocyanins":1.76,"Color_intensity":4.5,"Hue":1.25,"OD280\\/OD315_of_diluted_wines":3.4,"Proline":915},{"Class":1,"Alcohol":14.02,"Malic_acid":1.68,"Ash":2.21,"Alcalinity_of_ash":16.0,"Magnesium":96,"Total_phenols":2.65,"Flavanoids":2.33,"Nonflavanoid_phenols":0.26,"Proanthocyanins":1.98,"Color_intensity":4.7,"Hue":1.04,"OD280\\/OD315_of_diluted_wines":3.59,"Proline":1035},{"Class":1,"Alcohol":13.73,"Malic_acid":1.5,"Ash":2.7,"Alcalinity_of_ash":22.5,"Magnesium":101,"Total_phenols":3.0,"Flavanoids":3.25,"Nonflavanoid_phenols":0.29,"Proanthocyanins":2.38,"Color_intensity":5.7,"Hue":1.19,"OD280\\/OD315_of_diluted_wines":2.71,"Proline":1285},{"Class":1,"Alcohol":13.58,"Malic_acid":1.66,"Ash":2.36,"Alcalinity_of_ash":19.1,"Magnesium":106,"Total_phenols":2.86,"Flavanoids":3.19,"Nonflavanoid_phenols":0.22,"Proanthocyanins":1.95,"Color_intensity":6.9,"Hue":1.09,"OD280\\/OD315_of_diluted_wines":2.88,"Proline":1515},{"Class":1,"Alcohol":13.68,"Malic_acid":1.83,"Ash":2.36,"Alcalinity_of_ash":17.2,"Magnesium":104,"Total_phenols":2.42,"Flavanoids":2.69,"Nonflavanoid_phenols":0.42,"Proanthocyanins":1.97,"Color_intensity":3.84,"Hue":1.23,"OD280\\/OD315_of_diluted_wines":2.87,"Proline":990},{"Class":1,"Alcohol":13.76,"Malic_acid":1.53,"Ash":2.7,"Alcalinity_of_ash":19.5,"Magnesium":132,"Total_phenols":2.95,"Flavanoids":2.74,"Nonflavanoid_phenols":0.5,"Proanthocyanins":1.35,"Color_intensity":5.4,"Hue":1.25,"OD280\\/OD315_of_diluted_wines":3.0,"Proline":1235},{"Class":1,"Alcohol":13.51,"Malic_acid":1.8,"Ash":2.65,"Alcalinity_of_ash":19.0,"Magnesium":110,"Total_phenols":2.35,"Flavanoids":2.53,"Nonflavanoid_phenols":0.29,"Proanthocyanins":1.54,"Color_intensity":4.2,"Hue":1.1,"OD280\\/OD315_of_diluted_wines":2.87,"Proline":1095},{"Class":1,"Alcohol":13.48,"Malic_acid":1.81,"Ash":2.41,"Alcalinity_of_ash":20.5,"Magnesium":100,"Total_phenols":2.7,"Flavanoids":2.98,"Nonflavanoid_phenols":0.26,"Proanthocyanins":1.86,"Color_intensity":5.1,"Hue":1.04,"OD280\\/OD315_of_diluted_wines":3.47,"Proline":920},{"Class":1,"Alcohol":13.28,"Malic_acid":1.64,"Ash":2.84,"Alcalinity_of_ash":15.5,"Magnesium":110,"Total_phenols":2.6,"Flavanoids":2.68,"Nonflavanoid_phenols":0.34,"Proanthocyanins":1.36,"Color_intensity":4.6,"Hue":1.09,"OD280\\/OD315_of_diluted_wines":2.78,"Proline":880},{"Class":1,"Alcohol":13.05,"Malic_acid":1.65,"Ash":2.55,"Alcalinity_of_ash":18.0,"Magnesium":98,"Total_phenols":2.45,"Flavanoids":2.43,"Nonflavanoid_phenols":0.29,"Proanthocyanins":1.44,"Color_intensity":4.25,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":2.51,"Proline":1105},{"Class":1,"Alcohol":13.07,"Malic_acid":1.5,"Ash":2.1,"Alcalinity_of_ash":15.5,"Magnesium":98,"Total_phenols":2.4,"Flavanoids":2.64,"Nonflavanoid_phenols":0.28,"Proanthocyanins":1.37,"Color_intensity":3.7,"Hue":1.18,"OD280\\/OD315_of_diluted_wines":2.69,"Proline":1020},{"Class":1,"Alcohol":14.22,"Malic_acid":3.99,"Ash":2.51,"Alcalinity_of_ash":13.2,"Magnesium":128,"Total_phenols":3.0,"Flavanoids":3.04,"Nonflavanoid_phenols":0.2,"Proanthocyanins":2.08,"Color_intensity":5.1,"Hue":0.89,"OD280\\/OD315_of_diluted_wines":3.53,"Proline":760},{"Class":1,"Alcohol":13.56,"Malic_acid":1.71,"Ash":2.31,"Alcalinity_of_ash":16.2,"Magnesium":117,"Total_phenols":3.15,"Flavanoids":3.29,"Nonflavanoid_phenols":0.34,"Proanthocyanins":2.34,"Color_intensity":6.13,"Hue":0.95,"OD280\\/OD315_of_diluted_wines":3.38,"Proline":795},{"Class":1,"Alcohol":13.41,"Malic_acid":3.84,"Ash":2.12,"Alcalinity_of_ash":18.8,"Magnesium":90,"Total_phenols":2.45,"Flavanoids":2.68,"Nonflavanoid_phenols":0.27,"Proanthocyanins":1.48,"Color_intensity":4.28,"Hue":0.91,"OD280\\/OD315_of_diluted_wines":3.0,"Proline":1035},{"Class":1,"Alcohol":13.88,"Malic_acid":1.89,"Ash":2.59,"Alcalinity_of_ash":15.0,"Magnesium":101,"Total_phenols":3.25,"Flavanoids":3.56,"Nonflavanoid_phenols":0.17,"Proanthocyanins":1.7,"Color_intensity":5.43,"Hue":0.88,"OD280\\/OD315_of_diluted_wines":3.56,"Proline":1095},{"Class":1,"Alcohol":13.24,"Malic_acid":3.98,"Ash":2.29,"Alcalinity_of_ash":17.5,"Magnesium":103,"Total_phenols":2.64,"Flavanoids":2.63,"Nonflavanoid_phenols":0.32,"Proanthocyanins":1.66,"Color_intensity":4.36,"Hue":0.82,"OD280\\/OD315_of_diluted_wines":3.0,"Proline":680},{"Class":1,"Alcohol":13.05,"Malic_acid":1.77,"Ash":2.1,"Alcalinity_of_ash":17.0,"Magnesium":107,"Total_phenols":3.0,"Flavanoids":3.0,"Nonflavanoid_phenols":0.28,"Proanthocyanins":2.03,"Color_intensity":5.04,"Hue":0.88,"OD280\\/OD315_of_diluted_wines":3.35,"Proline":885},{"Class":1,"Alcohol":14.21,"Malic_acid":4.04,"Ash":2.44,"Alcalinity_of_ash":18.9,"Magnesium":111,"Total_phenols":2.85,"Flavanoids":2.65,"Nonflavanoid_phenols":0.3,"Proanthocyanins":1.25,"Color_intensity":5.24,"Hue":0.87,"OD280\\/OD315_of_diluted_wines":3.33,"Proline":1080},{"Class":1,"Alcohol":14.38,"Malic_acid":3.59,"Ash":2.28,"Alcalinity_of_ash":16.0,"Magnesium":102,"Total_phenols":3.25,"Flavanoids":3.17,"Nonflavanoid_phenols":0.27,"Proanthocyanins":2.19,"Color_intensity":4.9,"Hue":1.04,"OD280\\/OD315_of_diluted_wines":3.44,"Proline":1065},{"Class":1,"Alcohol":13.9,"Malic_acid":1.68,"Ash":2.12,"Alcalinity_of_ash":16.0,"Magnesium":101,"Total_phenols":3.1,"Flavanoids":3.39,"Nonflavanoid_phenols":0.21,"Proanthocyanins":2.14,"Color_intensity":6.1,"Hue":0.91,"OD280\\/OD315_of_diluted_wines":3.33,"Proline":985},{"Class":1,"Alcohol":14.1,"Malic_acid":2.02,"Ash":2.4,"Alcalinity_of_ash":18.8,"Magnesium":103,"Total_phenols":2.75,"Flavanoids":2.92,"Nonflavanoid_phenols":0.32,"Proanthocyanins":2.38,"Color_intensity":6.2,"Hue":1.07,"OD280\\/OD315_of_diluted_wines":2.75,"Proline":1060},{"Class":1,"Alcohol":13.94,"Malic_acid":1.73,"Ash":2.27,"Alcalinity_of_ash":17.4,"Magnesium":108,"Total_phenols":2.88,"Flavanoids":3.54,"Nonflavanoid_phenols":0.32,"Proanthocyanins":2.08,"Color_intensity":8.9,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":3.1,"Proline":1260},{"Class":1,"Alcohol":13.05,"Malic_acid":1.73,"Ash":2.04,"Alcalinity_of_ash":12.4,"Magnesium":92,"Total_phenols":2.72,"Flavanoids":3.27,"Nonflavanoid_phenols":0.17,"Proanthocyanins":2.91,"Color_intensity":7.2,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":2.91,"Proline":1150},{"Class":1,"Alcohol":13.83,"Malic_acid":1.65,"Ash":2.6,"Alcalinity_of_ash":17.2,"Magnesium":94,"Total_phenols":2.45,"Flavanoids":2.99,"Nonflavanoid_phenols":0.22,"Proanthocyanins":2.29,"Color_intensity":5.6,"Hue":1.24,"OD280\\/OD315_of_diluted_wines":3.37,"Proline":1265},{"Class":1,"Alcohol":13.82,"Malic_acid":1.75,"Ash":2.42,"Alcalinity_of_ash":14.0,"Magnesium":111,"Total_phenols":3.88,"Flavanoids":3.74,"Nonflavanoid_phenols":0.32,"Proanthocyanins":1.87,"Color_intensity":7.05,"Hue":1.01,"OD280\\/OD315_of_diluted_wines":3.26,"Proline":1190},{"Class":1,"Alcohol":13.77,"Malic_acid":1.9,"Ash":2.68,"Alcalinity_of_ash":17.1,"Magnesium":115,"Total_phenols":3.0,"Flavanoids":2.79,"Nonflavanoid_phenols":0.39,"Proanthocyanins":1.68,"Color_intensity":6.3,"Hue":1.13,"OD280\\/OD315_of_diluted_wines":2.93,"Proline":1375},{"Class":1,"Alcohol":13.74,"Malic_acid":1.67,"Ash":2.25,"Alcalinity_of_ash":16.4,"Magnesium":118,"Total_phenols":2.6,"Flavanoids":2.9,"Nonflavanoid_phenols":0.21,"Proanthocyanins":1.62,"Color_intensity":5.85,"Hue":0.92,"OD280\\/OD315_of_diluted_wines":3.2,"Proline":1060},{"Class":1,"Alcohol":13.56,"Malic_acid":1.73,"Ash":2.46,"Alcalinity_of_ash":20.5,"Magnesium":116,"Total_phenols":2.96,"Flavanoids":2.78,"Nonflavanoid_phenols":0.2,"Proanthocyanins":2.45,"Color_intensity":6.25,"Hue":0.98,"OD280\\/OD315_of_diluted_wines":3.03,"Proline":1120},{"Class":1,"Alcohol":14.22,"Malic_acid":1.7,"Ash":2.3,"Alcalinity_of_ash":16.3,"Magnesium":118,"Total_phenols":3.2,"Flavanoids":3.0,"Nonflavanoid_phenols":0.26,"Proanthocyanins":2.03,"Color_intensity":6.38,"Hue":0.94,"OD280\\/OD315_of_diluted_wines":3.31,"Proline":970},{"Class":1,"Alcohol":13.29,"Malic_acid":1.97,"Ash":2.68,"Alcalinity_of_ash":16.8,"Magnesium":102,"Total_phenols":3.0,"Flavanoids":3.23,"Nonflavanoid_phenols":0.31,"Proanthocyanins":1.66,"Color_intensity":6.0,"Hue":1.07,"OD280\\/OD315_of_diluted_wines":2.84,"Proline":1270},{"Class":1,"Alcohol":13.72,"Malic_acid":1.43,"Ash":2.5,"Alcalinity_of_ash":16.7,"Magnesium":108,"Total_phenols":3.4,"Flavanoids":3.67,"Nonflavanoid_phenols":0.19,"Proanthocyanins":2.04,"Color_intensity":6.8,"Hue":0.89,"OD280\\/OD315_of_diluted_wines":2.87,"Proline":1285},{"Class":2,"Alcohol":12.37,"Malic_acid":0.94,"Ash":1.36,"Alcalinity_of_ash":10.6,"Magnesium":88,"Total_phenols":1.98,"Flavanoids":0.57,"Nonflavanoid_phenols":0.28,"Proanthocyanins":0.42,"Color_intensity":1.95,"Hue":1.05,"OD280\\/OD315_of_diluted_wines":1.82,"Proline":520},{"Class":2,"Alcohol":12.33,"Malic_acid":1.1,"Ash":2.28,"Alcalinity_of_ash":16.0,"Magnesium":101,"Total_phenols":2.05,"Flavanoids":1.09,"Nonflavanoid_phenols":0.63,"Proanthocyanins":0.41,"Color_intensity":3.27,"Hue":1.25,"OD280\\/OD315_of_diluted_wines":1.67,"Proline":680},{"Class":2,"Alcohol":12.64,"Malic_acid":1.36,"Ash":2.02,"Alcalinity_of_ash":16.8,"Magnesium":100,"Total_phenols":2.02,"Flavanoids":1.41,"Nonflavanoid_phenols":0.53,"Proanthocyanins":0.62,"Color_intensity":5.75,"Hue":0.98,"OD280\\/OD315_of_diluted_wines":1.59,"Proline":450},{"Class":2,"Alcohol":13.67,"Malic_acid":1.25,"Ash":1.92,"Alcalinity_of_ash":18.0,"Magnesium":94,"Total_phenols":2.1,"Flavanoids":1.79,"Nonflavanoid_phenols":0.32,"Proanthocyanins":0.73,"Color_intensity":3.8,"Hue":1.23,"OD280\\/OD315_of_diluted_wines":2.46,"Proline":630},{"Class":2,"Alcohol":12.37,"Malic_acid":1.13,"Ash":2.16,"Alcalinity_of_ash":19.0,"Magnesium":87,"Total_phenols":3.5,"Flavanoids":3.1,"Nonflavanoid_phenols":0.19,"Proanthocyanins":1.87,"Color_intensity":4.45,"Hue":1.22,"OD280\\/OD315_of_diluted_wines":2.87,"Proline":420},{"Class":2,"Alcohol":12.17,"Malic_acid":1.45,"Ash":2.53,"Alcalinity_of_ash":19.0,"Magnesium":104,"Total_phenols":1.89,"Flavanoids":1.75,"Nonflavanoid_phenols":0.45,"Proanthocyanins":1.03,"Color_intensity":2.95,"Hue":1.45,"OD280\\/OD315_of_diluted_wines":2.23,"Proline":355},{"Class":2,"Alcohol":12.37,"Malic_acid":1.21,"Ash":2.56,"Alcalinity_of_ash":18.1,"Magnesium":98,"Total_phenols":2.42,"Flavanoids":2.65,"Nonflavanoid_phenols":0.37,"Proanthocyanins":2.08,"Color_intensity":4.6,"Hue":1.19,"OD280\\/OD315_of_diluted_wines":2.3,"Proline":678},{"Class":2,"Alcohol":13.11,"Malic_acid":1.01,"Ash":1.7,"Alcalinity_of_ash":15.0,"Magnesium":78,"Total_phenols":2.98,"Flavanoids":3.18,"Nonflavanoid_phenols":0.26,"Proanthocyanins":2.28,"Color_intensity":5.3,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":3.18,"Proline":502},{"Class":2,"Alcohol":12.37,"Malic_acid":1.17,"Ash":1.92,"Alcalinity_of_ash":19.6,"Magnesium":78,"Total_phenols":2.11,"Flavanoids":2.0,"Nonflavanoid_phenols":0.27,"Proanthocyanins":1.04,"Color_intensity":4.68,"Hue":1.12,"OD280\\/OD315_of_diluted_wines":3.48,"Proline":510},{"Class":2,"Alcohol":13.34,"Malic_acid":0.94,"Ash":2.36,"Alcalinity_of_ash":17.0,"Magnesium":110,"Total_phenols":2.53,"Flavanoids":1.3,"Nonflavanoid_phenols":0.55,"Proanthocyanins":0.42,"Color_intensity":3.17,"Hue":1.02,"OD280\\/OD315_of_diluted_wines":1.93,"Proline":750},{"Class":2,"Alcohol":12.21,"Malic_acid":1.19,"Ash":1.75,"Alcalinity_of_ash":16.8,"Magnesium":151,"Total_phenols":1.85,"Flavanoids":1.28,"Nonflavanoid_phenols":0.14,"Proanthocyanins":2.5,"Color_intensity":2.85,"Hue":1.28,"OD280\\/OD315_of_diluted_wines":3.07,"Proline":718},{"Class":2,"Alcohol":12.29,"Malic_acid":1.61,"Ash":2.21,"Alcalinity_of_ash":20.4,"Magnesium":103,"Total_phenols":1.1,"Flavanoids":1.02,"Nonflavanoid_phenols":0.37,"Proanthocyanins":1.46,"Color_intensity":3.05,"Hue":0.906,"OD280\\/OD315_of_diluted_wines":1.82,"Proline":870},{"Class":2,"Alcohol":13.86,"Malic_acid":1.51,"Ash":2.67,"Alcalinity_of_ash":25.0,"Magnesium":86,"Total_phenols":2.95,"Flavanoids":2.86,"Nonflavanoid_phenols":0.21,"Proanthocyanins":1.87,"Color_intensity":3.38,"Hue":1.36,"OD280\\/OD315_of_diluted_wines":3.16,"Proline":410},{"Class":2,"Alcohol":13.49,"Malic_acid":1.66,"Ash":2.24,"Alcalinity_of_ash":24.0,"Magnesium":87,"Total_phenols":1.88,"Flavanoids":1.84,"Nonflavanoid_phenols":0.27,"Proanthocyanins":1.03,"Color_intensity":3.74,"Hue":0.98,"OD280\\/OD315_of_diluted_wines":2.78,"Proline":472},{"Class":2,"Alcohol":12.99,"Malic_acid":1.67,"Ash":2.6,"Alcalinity_of_ash":30.0,"Magnesium":139,"Total_ph